### ISSUE TITLE
References in paper 10.1002/asi.20755 from author 0000-0003-0159-013X

### ISSUE THREAD

**Issue by aarontaycheehsien** [opencitations/croci#1]
https://doi.org/10.6084/m9.figshare.7712123.v1

**Comment by essepuntato** [comment]
HI @aarontaycheehsien 

Thanks for the links. However, there is a problem with the license, since we cannot ingest data that are not CC0 – the Figshare document attached reports a CC-BY license.

Would it be possible to share it as CC0 material?
Thanks again for your support.
Have a nice day :-)

**Comment by aarontaycheehsien** [comment]
> HI @aarontaycheehsien
> 
> Thanks for the links. However, there is a problem with the license, since we cannot ingest data that are not CC0 – the Figshare document attached reports a CC-BY license.
> 
> Would it be possible to share it as CC0 material?
> Thanks again for your support.
> Have a nice day :-)

Oops. Fixed - https://figshare.com/articles/References_in_10_1002_asi_20755_from_author_0000-0003-0159-013X/7712123/2

**Comment by essepuntato** [comment]
added
